 
version: '3'

services:
  mysql:
    image: mysql
    environment:
      MYSQL_DATABASE: 'booking'
      MYSQL_USER: 'booking'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - 3306:3306
    expose:
      - 3306
