version: "3"

services:
  app:
    image: tullingedk/booking:latest
    restart: always
    environment:
      MYSQL_HOST: "${MYSQL_HOST}"
      MYSQL_PASSWORD: "${MYSQL_PASSWORD}"
      GOOGLE_CLIENT_ID: "${GOOGLE_CLIENT_ID}"
      GOOGLE_CLIENT_SECRET: "${GOOGLE_CLIENT_SECRET}"
      GOOGLE_HOSTED_DOMAIN: "${GOOGLE_HOSTED_DOMAIN}"
      BACKEND_URL: "${BACKEND_URL}"
      FRONTEND_URL: "${FRONTEND_URL}"
      REGISTER_PASSWORD: "${REGISTER_PASSWORD}"
      SWISH_NAME: "${SWISH_NAME}"
      SWISH_PHONE: "${SWISH_PHONE}"
      EVENT_DATE: "${EVENT_DATE}"
      SECRET_KEY: "${SECRET_KEY}"
      OAUTHLIB_INSECURE_TRANSPORT: "${OAUTHLIB_INSECURE_TRANSPORT}"
      DISABLED: "${DISABLED}"
    ports:
      - "80:${PORT}"
    expose:
      - "${PORT}"
