version: '3'

services:
  app:
    image: tullingedk/booking:latest
    environment:
      MYSQL_HOST: '${MYSQL_HOST}'
      MYSQL_PASSWORD: '${MYSQL_PASSWORD}'
      GOOGLE_CLIENT_ID: '${GOOGLE_CLIENT_ID}'
      GOOGLE_CLIENT_SECRET: '${GOOGLE_CLIENT_SECRET}'
      GOOGLE_HOSTED_DOMAIN: '${GOOGLE_HOSTED_DOMAIN}'
      BACKEND_URL: '${BACKEND_URL}'
      FRONTEND_URL: '${FRONTEND_URL}'
      REGISTER_PASSWORD: '${REGISTER_PASSWORD}'
      SWISH_PHONE: '${SWISH_PHONE}'
      SECRET_KEY: '${SECRET_KEY}'
      PORT: 6000
    depends_on:
      - redis
    ports:
      - 6000:6000
    expose:
      - 6000
