export const USER_SET_EMAIL = "USER_SET_EMAIL";
export const USER_SET_NAME = "USER_SET_NAME";
export const USER_SET_CLASS = "USER_SET_CLASS";
export const SET_AUTHENTICATED = "SET_AUTHENTICATED";
export const SET_REGISTERED = "SET_REGISTERED";
